from drill.cmd.command_base import get_all_commands
from drill.cmd.list_decks import ListDecksCommand
from drill.cmd.create_deck import CreateDeckCommand
from drill.cmd.update_deck import UpdateDeckCommand
from drill.cmd.delete_deck import DeleteDeckCommand
from drill.cmd.list_cards import ListCardsCommand
from drill.cmd.create_card import CreateCardCommand
from drill.cmd.update_card import UpdateCardCommand
from drill.cmd.delete_card import DeleteCardCommand
from drill.cmd.study import StudyCommand
from drill.cmd.review import ReviewCommand
from drill.cmd.stats import StatsCommand
from drill.cmd.export import ExportCommand
__import__('drill.cmd.import', globals(), locals(), ['ImportCommand'])
